model_name_or_path: "unsloth/Meta-Llama-3.1-8B-Instruct"
dataset: "Vikhrmodels/GrandMaster-PRO-MAX"
train_only_on_completions: True
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
num_train_epochs: 1
save_strategy: "steps"
save_steps: 300
save_total_limit: 3
learning_rate: 0.00004
gradient_accumulation_steps: 8
gradient_checkpointing: True
logging_steps: 1
remove_unused_columns: True
dataloader_num_workers: 2
generate_eval_examples: False
evaluation_strategy: "steps"
eval_steps: 300
run_name: "sft-grndm-llama-3.1-unsloth-full"
output_dir: "/home/models/sft-grndm-llama-3.1-unsloth-full"
warmup_steps: 20
report_to: "wandb"
conversation_field: "conversation"
bf16: True
seed: 42
logging_first_step: True
use_peft: False
assistant_message_template: "<|start_header_id|>assistant<|end_header_id|>"
pad_token: "<|reserved_special_token_0|>"
eos_token: "<|eot_id|>"
chat_template: "{{ bos_token }}{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
force_chat_template: True