model_name_or_path: "Vikhrmodels/ControllableRM-Qwen2.5-1.5B"
dataset: "Vikhrmodels/rm_training_dataset_16_12_24"
test_size: 0.05
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
num_train_epochs: 1
save_strategy: "steps"
evaluation_strategy: "steps"
num_prompts: 2
dissim_coef: 0.2
prompt_len: 96
save_steps: 240
eval_steps: 80
save_only_model: True
save_total_limit: 10
learning_rate: 0.002
weight_decay: 0.01
lr_scheduler_type: "cosine"
warmup_ratio: 0.01
center_rewards_coefficient: 0.01
gradient_accumulation_steps: 4
gradient_checkpointing: True
logging_steps: 1
remove_unused_columns: True
dataloader_num_workers: 2
max_length: 16384
attn_implementation: "sdpa"
torch_compile: False
run_name: "controllable-rm-qwen-1.5b-prompts-optimization-np2-dc0.2-pl96"
output_dir: "checkpoints/controllable-rm-qwen-1.5b-prompts-optimization-np2-dc0.2-pl96"
report_to: "wandb"
bf16: True
fp16: False
seed: 42
logging_first_step: True
pad_token: "<|image_pad|>"
eos_token: "<|im_end|>"
chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|im_start|>' + message['role'] + '\n' + message['content'] | trim + '<|im_end|>' %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant<|im_end|>\n' }}{% endif %}"
force_chat_template: False