model_name_or_path: "unsloth/Meta-Llama-3.1-8B"
dataset: "Vikhrmodels/ru-arena-general-rankings"
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
num_train_epochs: 1
save_strategy: "steps"
save_steps: 100
save_total_limit: 6
learning_rate: 0.0004
gradient_accumulation_steps: 8
gradient_checkpointing: True
logging_steps: 1
remove_unused_columns: True
dataloader_num_workers: 2
max_length: 8192
test_size: 0.05
evaluation_strategy: "steps"
eval_steps: 100
run_name: "rm-arena-llama-3.1-unsloth-lora-32-qkvogud"
output_dir: "/home/models/rm-arena-llama-3.1-unsloth-lora-32-qkvogud"
warmup_steps: 20
report_to: "wandb"
bf16: True
seed: 42
logging_first_step: True
use_peft: True
lora_task_type: SEQ_CLS
lora_target_modules:
  - "k_proj"
  - "v_proj"
  - "q_proj"
  - "o_proj"
  - "gate_proj"
  - "up_proj"
  - "down_proj"
lora_modules_to_save:
  - "score"
lora_r: 32
lora_alpha: 32
pad_token: "<|reserved_special_token_0|>"
eos_token: "<|eot_id|>"
chat_template: "{{ bos_token }}{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
force_chat_template: True